### ISSUE TITLE
Improper formatted "from" header silently fails

### ISSUE THREAD

**Issue by charliemitchell** [maildev/maildev#148]
Hello, I noticed that if you improperly format the `from` header that the message does not get delivered to the UI. As strange as this sounds, and obviously a mistake on the developer side, It would be nice to either deliver it with an "error" flag/icon or deliver a message undeliverable to the UI with an explanation.

As an example, if you were to send the following as the from header,
```
<John Do>noreply@homelight.com
```
Instead of 
```
John Do<noreply@homelight.com>
```
The message won't make it into the UI. And then the debugging process include topics such as... 
Is maildev running? Is maildev working? Maybe i'll restart maildev. Is there something wrong with the email? Looks fine to me. Is anything listening to port 1025? ok, 1080? Am i still configured to use 1025 in the application? Try a different mail interceptor, that got delivered, ok maybe it's maildev.. but why? Looks at email again, hmmm... aha! There's a bug in the from header! So Simple! How could I have not seen it! You get the point. I think that since this is a great development tool, why not catch some of these issues, we all do weird stuff sometimes.

**Comment by charliemitchell** [comment]
PING! Seems like this project may be dead? I have not seen any commits in a while.

**Comment by donut87** [comment]
Hey Charlie, 
This project is not dead. It's just gotten a little quiet ;) 
Do I understand correctly, that your main concern are validations (headers and other stuff with rules)?

**Comment by charliemitchell** [comment]
Hi! Thanks for getting back to me on this. You are correct, It would be nice if MailDev analyzed the headers and other stuff with rules. This would be great to aid in the development process. IMHO it would be really cool if there was a validation stage that validated such things and any mail that did not pass the validation got delivered with an error flag, and an array of errors encountered throughout the process.

**Comment by kgeis** [comment]
I think that the proper thing for MailDev to do would be to reject the email.
