### ISSUE TITLE
Enabling/disabling javascript

### ISSUE THREAD

**Issue by way2key** [maildev/maildev#152]
I was testing my website against xss and for fun I tried to sent a mail with some JavaScript inside.
Suddenly, when I clicked on that mail the JavaScript code executed himself. :bowtie:
In production (of course because js is disabled in mails) this is impossible but for testing purpose, I wish you can prevent JS from executing when you click on a mail. 
I think this is contradictory because Mail Dev run on node... 
At least have you any Idea to fix this small glitch?:beetle:

++ Way2key

**Comment by djfarrelly** [comment]
Fixed with #181
