### ISSUE TITLE
MailDev (UI) only shows mail of first recipient when using nodemailer and more then one to address

### ISSUE THREAD

**Issue by OliverFischer** [maildev/maildev#154]
Hi, 

when running maildev and sending mails via nodemailer to more than one person maildev only shows up the first e mail / sent to the first recipient. When using nodemailer with to property containing more than one person with a regular smtp server, mails are sent to all persons in the to list. May be I missed something ?

Greetings

**Comment by dachinat** [comment]
Did anyone find solution to this?

When using nodemailer and you send to more than one recipient you get just one message in inbox. I have checked with Rails and in this situation, opposed to nodemailer, there were more than one incoming messages in ui inbox.

**Comment by cyberram** [comment]
I don't think it's to do with nodemailer. Looks like MailDev catches and just stores these emails with multiple recipients. If you need to view it  in UI, you can open the email and use _Display->Headers_ to view full header of email.

**Comment by oktapodia** [comment]
Sorry it's been a long time ago, I'm gonna investigate into that

**Comment by davidhenley** [comment]
+1

**Comment by davidhenley** [comment]
Any update?

**Comment by kl3sk** [comment]
Hello,

It look like this is always the case 

Version: `You are running MailDev 1.1.0`

If this is confirmed for Maildev, it is not a real problem on a production env.

**Comment by DominikSerafin** [comment]
Fixed, more info here → https://github.com/maildev/maildev/issues/335#issuecomment-764992941

**Comment by davidhenley** [comment]
Awesome. Thanks @dominikserafin
