### ISSUE TITLE
Support for TLS (via ngrok or somehow?)

### ISSUE THREAD

**Issue by bcardiff** [maildev/maildev#182]
On some services to allow custom smtp server, TLS is required. auth0.com is one example.

It seems that TLS is not supported in MailDev, so I thought of trying ngrok (pro account) to use tls

```
# start docker image
$ docker run --rm -p 1080:1080 -p 1025:1025 djfarrelly/maildev bin/maildev --web 1080 --smtp 1025 --incoming-user smtp --incoming-pass smtp

# start ngrok tunnel
$ ngrok tls -subdomain=SUBDOMAIN 1025
Forwarding                    tls://SUBDOMAIN.ngrok.io -> localhost:1025 

# manual check for connection
$ /usr/local/opt/openssl/bin/openssl s_client -starttls smtp -crlf -connect SUBDOMAIN.ngrok.io:443
CONNECTED(00000003)
didn't found starttls in server response, try anyway...
140735930754056:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 343 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1496808447
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

So far I haven't been able to succeed. Is there a way you would suggest to add TLS over MailDev? It would be great for this development environment (ie: external service that really want TLS).

Thanks!

**Comment by kajmagnus** [comment]
Yes this would be great. Just started using MailDev in order to test STARTTLS, and then noticed that it doesn't support TLS :- P

**Comment by bcardiff** [comment]
@kajmagnus maybe it will helps your use case. I use for some projects a small smtp server that supports tls and redirects to other smtp https://github.com/zixia/docker-simple-mail-forwarder .

I use it for actual emails, but maybe it can be chained to MailDev.

**Comment by kajmagnus** [comment]
@bcardiff Thanks for the tips. I'll wait for a while and see what happens with MailDev + TLS and some other projects, e.g. MailSlurper seems to support TLS but has a broken Docker build.  ... If nothing happens, I'll try Simple Mail Forwarder  :- )

**Comment by JeeDay** [comment]
Hi guys,
What's up ? there is no news about supporting tls in maildev.
This tool is really useful and is downloaded a lot.
but the issues have no responses...
If you want to do something open source and share it with the community,
you should be ready to request at least to issues.
just by a "For now I have no time" or "something"...

**Comment by xoroz** [comment]
Hi everyone,

Up for SMTP with TLS
please add the functionality

**Comment by djfarrelly** [comment]
@xoroz I'm a bit rusty on some of these things, do you think #224 will address this issue?
