### ISSUE TITLE
any plan to support bcc?

### ISSUE THREAD

**Issue by kimhanjoon** [maildev/maildev#233]
Is there any plan to support bcc?

**Comment by kgeis** [comment]
What do you mean by "support"?.

**Comment by kimhanjoon** [comment]
When I send a mail to maildev server with bcc, maildev doesn't have bcc information. (or am I talking wrong?)
If maildev had bcc information, you would say "maildev supports bcc".

**Comment by kgeis** [comment]
Thank you for the clarification. To explain my question, I could have imagined you want to bcc some address when relaying email.

**Comment by refractalize** [comment]
would be good to see the SMTP "envelope" in the "Display" menu, i.e. the `MAIL FROM`, `RCPT TO` instructions (including BCC addresses) used when sending the email.

**Comment by aandis** [comment]
+1

**Comment by soulteary** [comment]
A community user submitted a functional implementation of bcc https://github.com/maildev/maildev/pull/369 , we will release it together in v2.0.2 version.

However, there are currently some problems with the interface style. I don't think it is a big problem. We can improve it in the next version.

Hope this news is helpful to you @aandis @kimhanjoon @kgeis @refractalize
