### ISSUE TITLE
Change default Dockerfile port from 80/25

### ISSUE THREAD

**Issue by djfarrelly** [maildev/maildev#244]
### Purpose
I think it would better for Docker container security to not run the main command on a port under 1000. 

### Idea
Change the Dockerfile to run on 1080 / 1025 instead of 80 / 25. The challenge is that this could break people's usage when upgrading so we'd have to think about this one or save it for a 2.x breaking changes release.

**Comment by bearcodi** [comment]
Hi @djfarrelly I've created a pull request for this, I kept getting errors when using the docker image on Mac when I was trying to bind to port `25`

The pull request sets the default ports for web and smtp to 1080 and 1024 respectively.

Thanks for the cool project! Its in my dev/test toolkit by default!
