### ISSUE TITLE
maildev should not attempt to relay email without an unfiltered email

### ISSUE THREAD

**Issue by imaginejosephishak** [maildev/maildev#252]
I ran MailDev as follows:
node ./bin/maildev --base-pathname /maildev -w 80 -s 25 --outgoing-host 10.231.22.172 --auto-relay --auto-relay-rules /var/run/file.json -v

My file.json looks like the following:

[
  {
    "deny": "*"
  },
  {
    "allow": "myemail@gmail.com"
  }
]

My code sends a test email to "test@joseph.com" and has reply to set to "reply@joseph.com".  Both email addresses are filtered out (denied) according to the above rules, but for some reason maildev still attempts to send the email even though there are no recipients.  As a result, maildev crashes with an error such as:

Saving email: Change password, id: qO2b7EDb
Error when relaying email Email had no recipients
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected Response: 451 4.7.0 Timeout waiting for client input
    at SMTPConnection._processResponse (/usr/src/app/node_modules/smtp-connection/lib/smtp-connection.js:607:30)
    at SMTPConnection._onData (/usr/src/app/node_modules/smtp-connection/lib/smtp-connection.js:431:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:559:20)

This is incorrect behavior.  If all the addresses are filtered out, the email should not be relayed.

**Comment by constfilin-sgn** [comment]
I ran into the same issue.
When can it be fixed?

**Comment by constfilin-sgn** [comment]
I have a fix for this issue. How do I go about producing a PR? I do not seem to have right to create a new branch in MailDev repo.

**Comment by oktapodia** [comment]
Feel free to open a PR @constfilin-sgn, you have first to create a fork (top right button), then create your branch on your fork before opening the PR.

**Comment by constfilin-sgn** [comment]
@oktapodia : https://github.com/djfarrelly/MailDev/pull/275
