### ISSUE TITLE
Question before first use: can this project catch without send?

### ISSUE THREAD

**Issue by realtebo** [maildev/maildev#271]
I'm looking for a 'blackhole' like mailtrap , where email can be sent through the smtp, but the emails never reach the recipients, they are blocked into smtp. 

Is this the working mode of MailDev? Or mail dev smtp MUST send out mails?

**Comment by oktapodia** [comment]
This is exactly the purpose of MailDev, every email sent to the maildev SMTP server will only be stored into the maildev app.
