### ISSUE TITLE
STARTTLS should not be advertised  

### ISSUE THREAD

**Issue by lyrixx** [maildev/maildev#274]
Hello.

MailDev advertised a support for STARTTLS but when the client tries to upgrade the protocol, MailDev crash badly:

```
MailDev webapp running at http://0.0.0.0:80
MailDev SMTP Server running at 0.0.0.0:25
### Here is try to send an email 
Could not start mail server on undefined:undefined
Port already in use or insufficient rights to bind port
Recieved shutdown signal, shutting down now...
```

But If I ran maildev with `--hide-extensions STARTTLS` everything goes fine.
Since MailDev does not implement TLS, I think this option should be enabled by default.

You can find more information on Symfony [Pull Request](https://github.com/symfony/symfony/pull/34242)  I have open to fix Symfony. But we concluded the bug is not in Symfony but MailDev.

More over, all [examples](https://github.com/djfarrelly/MailDev#configure-your-project)  tell developers to disable TLS. I think it's an indicator that prove that this option should be disabled by default.

Thanks

**Comment by spipu** [comment]
i have the same issue (using MailDev + Symfony 4.4, and symfony try to start TLS connection, because it is returns by maildev in the capabilities).

=> when this MR will be merged and released ?

**Comment by lugus** [comment]
Having the same issue, any news?

**Comment by spike31** [comment]
Thx @lyrixx !

shell : `bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS`

or with docker-compose :

```bash
maildev:
    image: djfarrelly/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
```

**Comment by lyrixx** [comment]
@spike31 Thanks. I did that in my app. But this is not normal to have to do so because maildev does not support STARTTLS.

@jderusse did a great [PR](https://github.com/maildev/maildev/pull/276). Did you see it ?

**Comment by spike31** [comment]
No, but we will waiting for the merge! :ok_hand:

**Comment by SuperQ** [comment]
So, I'm not sure this is correct. In [Alertmanager](https://github.com/prometheus/alertmanager), we were using STARTLS just fine. But only without auth. According to our testing notes, STARTTLS works as long as it's not combined with auth.

So disabling it completely makes our tests not possible.
