### ISSUE TITLE
Github pages is down

### ISSUE THREAD

**Issue by alkaphreak** [maildev/maildev#277]
The link from your personal website is broken : https://danfarrelly.nyc/MailDev/

**Comment by kgeis** [comment]
This is a problem with Dan's personal site. Nothing we can change on this project will affect his site, so I am closing this issue. If you would like, file the issue on the repository for his personal site: [djfarrelly/djfarrelly.github.io](https://github.com/djfarrelly/djfarrelly.github.io)
