### ISSUE TITLE
Release of new version

### ISSUE THREAD

**Issue by ipoint-oss** [maildev/maildev#279]
I was wondering when a new version of the docker image will be released. Its been 5 months and it would be great to have access to the new features/bug fixes :)

**Comment by oktapodia** [comment]
Hello, sorry for the delay, I'll take care of it during this week

**Comment by lugus** [comment]
Any news?

**Comment by ipoint-oss** [comment]
I haven't seen anything. @oktapodia can we assist you with this in any way?

**Comment by djfarrelly** [comment]
I've published a new beta version with the new Docker image name: `maildev/maildev:2.0.0-beta1`. I'll work towards getting more features ready and tested for the full 2.0.0 stable release!

**Comment by RonNabuurs** [comment]
Any update on the state of 2.0.0, I can see there are still a few issues open.

**Comment by soulteary** [comment]
Sorry for the wait, the project wakes up. @ipoint-oss @lugus @RonNabuurs 

The original 2.0.0 plan of the project will be updated in the next 2.x version

We need more friends to play with https://github.com/maildev/maildev/issues/379
