### ISSUE TITLE
 Auto Relay rules and Docker

### ISSUE THREAD

**Issue by mikestreety** [maildev/maildev#286]
Hi, I'm fairly new to docker but want to use the MailDev image.

Do I just pass the parameters in as usual? I.e.

```
docker run -p 80:80 -p 1025:25 djfarrelly/maildev --web 80 --ip 10.0.0.34 --outgoing-host 10.0.0.2 --hide-extensions STARTTLS --auto-relay --auto-relay-rules /root/catch-mail/rules.json
```

My issue is that it can't find the `rules.json` and I can't work out how to make it find it.

Thanks for an awesome product!

**Comment by djfarrelly** [comment]
Hey @mikestreety, for the maildev command to find your file within your container, you need to mount the json file as a volume into the container itself. Here is the documentation from Docker on this: https://docs.docker.com/storage/volumes/
