### ISSUE TITLE
Cannot access maildev outside of docker [iMac]

### ISSUE THREAD

**Issue by pvinothit** [maildev/maildev#300]
I did tried to access maildev of docker in Mac but I can't.

I ran with this command `docker run -p 1080:1080 --name maildev maildev/maildev`

and tried with both local ip and dockerVM ip

http://localhost:1080
http://192.168.65.3:1080

Any help would be appreciated.

**Comment by leosuncin** [comment]
Possible duplicate of #307, see my comment for an explanation https://github.com/maildev/maildev/issues/307#issuecomment-674612343

**Comment by leosuncin** [comment]
Fix with: `docker run -p 1080:80 --name maildev maildev/maildev`

**Comment by pvinothit** [comment]
Thanks @leosuncin I found the answer way long ago. Sorry forget to close the issue. thanks
