### ISSUE TITLE
No option to configure web host ?

### ISSUE THREAD

**Issue by Cartman34** [maildev/maildev#325]
Hello,

I am currently using maildev with a domain mail.sowapps-web.local as apache2 HTTPS proxy to http://127.0.0.1:1080/
All my email attachments are not found because their urls are //127.0.0.1:1080/email/... and clearly 127.0.0.1:1080 is not valid on my host computer.

Is there any existing solution ? It seems not.

**Comment by kgeis** [comment]
It looks like the [URLs are relative](https://github.com/maildev/maildev/blob/52af9e6352c4ad2c3056e45ae0b1f70043ce4e82/app/views/item.html#L211). Do you have `ProxyPassReverse` set in your Apache configuration?

**Comment by Cartman34** [comment]
So I changed it to ProxyPassReverse / https://mail.sowapps-web.local/ which is the URL I am using to access it, I restarted Apache2 & Maildev with no more success.
You are pointing the link used in attachments tab and this link is fine.

**Comment by kgeis** [comment]
To make `req.headers.host` the name of your reverse proxy, try `ProxyPreserveHost on` in your Apache configuration.

**Comment by Cartman34** [comment]
Thank you, this is now working fine !
`ProxyPreserveHost on` is the solution to this issue !
