### ISSUE TITLE
Latest docker image not parsing environment variables

### ISSUE THREAD

**Issue by piotr-struzik** [maildev/maildev#326]
Thx for developing such a great tool 

I'm running maildev inside Kubernetes ( maildev/maildev image from docker hub)  and configuring it via environment variables ex. MAILDEV_WEB_USER and MAILDEV_WEB_PASS

It looks like those variables are not honored 

Checked the container and lib/options.js file (that parses env variables) is not there 

Possibly same issue as in https://github.com/maildev/maildev/issues/315

**Comment by nuxwin** [comment]
Any news about this issue?

**Comment by soulteary** [comment]
Thanks for the feedback, this problem should be caused by using an outdated docker image, we have updated a new version, which may be helpful to you.

@nuxwin @piotr-struzik
