### ISSUE TITLE
I've created a fork with improvements & PR merges

### ISSUE THREAD

**Issue by DominikSerafin** [maildev/maildev#335]
Hey all — I've created a fork of this project with various improvements and also some PR merges. You can check it out at [https://github.com/DominikSerafin/maildev](https://github.com/DominikSerafin/maildev).

I've created my own fork because this project seems abandoned, and I wanted some of the features that were not implemented (mostly persistent storage and some web interface fixes/polishes).

However, @djfarrelly @oktapodia if you're still maintaining this repo and are open to merging changes from my fork — let me know, and I'll open PR. I'd prefer not to fragment this project.

Screenshots of the refreshed web interface:

![web-ui-light](https://user-images.githubusercontent.com/7447244/103469537-5439a900-4d66-11eb-966d-e6097fa3820f.png)

![web-ui-dark](https://user-images.githubusercontent.com/7447244/103469538-556ad600-4d66-11eb-8bcb-124ac221c331.png)

**Comment by djfarrelly** [comment]
Hey @DominikSerafin, I have to admit that I no longer have the proper time to commit to this project and I completely agree with you that it's better to merge into this project rather than create a fork. From a quick overview, I like what you've done. How would you suggest we incorporate your changes? I see you've made some additional changes that I think would be good to not make in this upstream repo (e.g. README changes, removal of files like code climate).

**Comment by kl3sk** [comment]
Hello,

A dark mode will be at least a great addition.
Fixing https://github.com/maildev/maildev/issues/154 should be looked too

**Comment by DominikSerafin** [comment]
@djfarrelly happy to hear that! When I'll have some more free time (hopefully soon) I'll work on creating PR with only a subset of changes from my fork (so without changes to code climate, README, etc.) and full changelog. 

@kl3sk #154 is somewhat "fixed" in my fork, e.g. when there are 3 recipients, the sidebar item shows `TO: hello@example.com +2`. While it doesn't show all email addresses, at least there's some indication about that, and you can then check full headers in the raw email.

Seen here in the last item:
![103469538-556ad600-4d66-11eb-8bcb-124ac221c331](https://user-images.githubusercontent.com/7447244/105421978-44b1cf80-5c43-11eb-845a-7f7742121440.png)

**Comment by kl3sk** [comment]
Glad to here that. 

Is there a docker image of your fork. I'm interested in trying it and why not using it. Unless @djfarrelly decide to use some or all your features. 

Thanks

**Comment by DominikSerafin** [comment]
@kl3sk yup - https://hub.docker.com/r/dominikserafin/maildev

**Comment by djfarrelly** [comment]
Hey @DominikSerafin, after reviewing your work in the fork, I've given you write access to this repo. I know that it may take several PRs and some may need to be merged in a specific order. I wanted to allow you to move ahead without me or anyone else blocking you from getting your improvements into master. If you need me to push docker images or publish to NPM, please let me know!!

Also, if it helps longer term, we could set up Github actions with my tokens to push to Docker hub and npm (maybe Github packages too?). That could allow you or others to ship new functionality faster.

**Comment by kl3sk** [comment]
After testing @DominikSerafin fork. I can said it works without any issues for me.

**Comment by DominikSerafin** [comment]
@djfarrelly amazing, it will for sure make the process smoother. Thank you! 

As for Docker/NPM - it would of course help even more, but for now, I think it will suffice that I can just ping you whenever there will be any code ready for release.

**Comment by heldchen** [comment]
thanks all, this looks great! having these changes on npm would certainly be welcomed for users (like me) as well :)

**Comment by DominikSerafin** [comment]
Status update - almost finished with introducing the changes to this repo. Should have finishing touches done hopefully soon.

**Comment by heldchen** [comment]
awesome, looking forward to a new release! thanks for your work, very much appreciated!

**Comment by DominikSerafin** [comment]
Hey @djfarrelly I've introduced everything from my fork (with exception to the cleanups I did, like e.g. Codecov deletion).

On top of that, I've:

- Added a [load testing script](https://github.com/maildev/maildev/blob/96248f8c38bd269f541dd91e60ad560f57eb46a0/scripts/load-test.js)
- Fixed the email parsing & saving piping https://github.com/maildev/maildev/commit/43f97ae81e9154d19ef4333da00299a12af6fecb
- Merged PR that replaces Travis with GitHub Actions https://github.com/maildev/maildev/pull/333 https://github.com/maildev/maildev/commit/b25f8e3bf79ae391c6b12a50c468fd08af47e4f6
- Changed/fixed how some errors are handled https://github.com/maildev/maildev/commit/2581028b3e743aaf580361f64fd7d5c247c02e66 https://github.com/maildev/maildev/commit/7fa44ebc225786b9bd42ae65d8ea6e9a55fe7aa0
- Closed some issues & PRs, mostly those that were fixed by my changes
- Like already mentioned, refreshed the website https://github.com/maildev/maildev/pull/347

If you don't spot any new issues introduced by my changes I think we could release now the new MailDev version. Once that is up, I'll archive my fork.

**Comment by thirsch** [comment]
Fantastic addons in the fork! Any update on the status of releasing a new version here?

**Comment by a-h-abid** [comment]
Hi @DominikSerafin , Have you made any new releases for this repo ?

**Comment by DominikSerafin** [comment]
@a-h-abid I only have collaborator access to commit code to this repo. I'm unable to release a new version to npm/Docker.

**Comment by kl3sk** [comment]
@DominikSerafin you said that #154 was fixed at least. And it is. But could you consider an option to not group them ?

**Comment by thirsch** [comment]
Hi @djfarrelly, do you see any chance to give more permissions to @DominikSerafin? It's very sad to see this great project dying...

**Comment by DominikSerafin** [comment]
@kl3sk I don't plan to do any more work or maintenance on maildev any time soon.

So, @thirsch, with that in mind, if @djfarrelly could publish the recent changes as a new release on npm/Docker, I'm not sure if I need any additional permissions or access.

**Comment by LoneRifle** [comment]
Hello @djfarrelly ,

The Open Government Products group in Singapore (@opengovsg) are regular users of maildev and would like to assume responsibilities to maintain this repository and publish changes to npm and Docker Hub. 

The specific individuals that we hope you would grant relevant access to are:

@LoneRifle (myself)  
@liangyuanruo  
@seaerchin

Echoing @thirsch , we would be likewise a little sad if the work done by @DominikSerafin and others is in vain, and would like to continue stewardship of this package that you have created. We also have a [fork](https://github.com/opengovsg/maildev) that we can fall back on for our own needs, but would love the opportunity to keep the canonical package going.

**Comment by jgonera** [comment]
@djfarrelly Could we give people mentioned by @LoneRifle access so that they can maintain the project and upload new Docker images?

**Comment by idears-org** [comment]
> @djfarrelly Could you give people mentioned by @LoneRifle access so that they can maintain the project and upload new Docker images?

Their fork was archived.

**Comment by jgonera** [comment]
@LoneRifle does that mean you have permissions for this repo now? If yes, could you upload a new Docker image?

**Comment by soulteary** [comment]
@DominikSerafin Hi 👋, It looks like we did two forks. 

I'm thinking of fully containerizing this project with web hooks, maybe in the near future I can replace maildev src with your project.

my repo: https://github.com/soulteary/maildev

**Comment by heldchen** [comment]
would be nice if one of the forks could also push their updated code to the npm repository (https://www.npmjs.com/search?q=maildev) for the end users :)

**Comment by LoneRifle** [comment]
> @DominikSerafin Hi 👋, It looks like we did two forks.
> 
> I'm thinking of fully containerizing this project with web hooks, maybe in the near future I can replace maildev src with your project.
> 
> my repo: https://github.com/soulteary/maildev

I've ported a new feature I added to our fork and filed a PR against your repo. Hope you get round to reviewing it soon!

**Comment by soulteary** [comment]
Sorry for the late reply, I just saw your message when I was just cleaning up my unread messages. @djfarrelly 

I'd love to be part of every community, sharing and perfecting the good stuff. 🍻 

The current project does lack a small virtual team for maintenance and management, so if several people can maintain it together, it should be the best choice for the project. But I'm not sure how this small team will maintain relatively smooth communication next, and relying solely on GitHub reminders will not be timely.

If you want to quickly change the status of the project, perhaps the most direct way is to quickly reach an agreement with a small team, confirm what the project will not do next, reply to users clearly, and maintain a relatively healthy continuous update and release.

I am currently using a software called lark (similar to slack) at work, which can maintain relatively fast communication with overseas colleagues, as well as leave messages offline.  I don't know if you guys will like this. I would love to hear other people's views and suggestions.

**Comment by LoneRifle** [comment]
I wouldn't mind. Having the ability to publish the nom package would be helpful too!

**Comment by djfarrelly** [comment]
@LoneRifle @soulteary @DominikSerafin - I have invited you each to the Maildev Github organization team called "Contributors." While I think a real-time communication tool like Lark or Slack could work, I think the real-time nature and various working time zones may make that difficult. 

Github teams have built in message boards which can allow us to have discussions on what to do next and help coordinate the project outside of the confines of a pull request or an issue. I think this could be a good for us to coordinate on. If others want to support the project or join in discussions, we can bring them in over time. Here's a direct link to the group message board that I invited you all to:

https://github.com/orgs/maildev/teams/contributors/discussions

I'll kick off a couple threads to get started, but feel free to open your own discussion if you want to discuss or ask about something specifically, e.g. npm publish access.

Thanks for your interest!!

**Comment by LoneRifle** [comment]
@djfarrelly thanks for the invite! @soulteary - I'm leaving it to you to file the PR from your fork to merge our changes back into this repo.

**Comment by Zerotask** [comment]
Any updates on this?

**Comment by djfarrelly** [comment]
Most of these changes have been merged and were released as part of the 2.0 release in May 2022. 

See: https://github.com/maildev/maildev/releases

I'm going to close this and if there is a specific change that is requested, we should open a separate issue or PR.
