### ISSUE TITLE
Is maildev dead? No future maintenance? EOL?

### ISSUE THREAD

**Issue by 4n4n4s** [maildev/maildev#339]
Hi, 
as maildev is a cool tool and there are a lot of open PR and issues I would like to know if it is more or less dead?

Would be good to have some patches and fixes like dependency upgrades for security reasons but also API extension so that you can use it for tests and so on and forth.

Release 2.0 is in beta for a year but nothing has really moved there too on [dockerhub](https://hub.docker.com/r/maildev/maildev/tags?page=1&ordering=last_updated) for example.

As I think a lot of people are using this tool it would be good to have it still maintained.

Thank you in advance :)

**Comment by splitt3r** [comment]
https://github.com/maildev/maildev/issues/335#issuecomment-755353611 should answer that question partly.

**Comment by soulteary** [comment]
It slept, but woke up, let's play together @4n4n4s @splitt3r  https://github.com/maildev/maildev/issues/379

and we updated a new version docker image, hope it helps you @4n4n4s 
https://github.com/maildev/maildev/issues/382
