### ISSUE TITLE
Wsl Docker setup

### ISSUE THREAD

**Issue by veritem** [maildev/maildev#345]
I'm developing on my windows machine with  WSL enabled. Running `docker run -p 1080:1080 --name maildev maildev/maildev`  starts but doesn't work even opening the web UI doesn't work

**Comment by elhose** [comment]
I have the same issue here, I tried setting enviroment variables (-e MAILDEV_WEB_PORT=1080 or -w 1080) and I too can't make that work

**Comment by DominikSerafin** [comment]
Using the latest version works for me on WSL Docker Desktop. 

`docker run -p 1080:1080 --name maildev maildev/maildev:2.0.0-beta3`

**Comment by DominikSerafin** [comment]
@elhose I might be able to help you, but I need more details.

**Comment by DennisMaas** [comment]
Same here. I tried yyour suggestion but it just gives me a "page not available".
I deleted the image and installed maildev using `$ npm install -g maildev`. I can start maildev and it says
```
MailDev webapp running at http://0.0.0.0:1080
MailDev SMTP Server running at 0.0.0.0:1025
```
but I still get the same blank page. 
Which infos do you need?

**Comment by DennisMaas** [comment]
Okay, just for fun I tried `localhost:1080` instead of `0.0.0.0:1080` that I saw in the doc and in some videos. Now it´s working with the npm version and probably with docker too.

**Comment by johnny-silverhand** [comment]
WSL2. I have same problem. I changed port from 1080 to 8080. It worked for me.

`docker run -p 8080:80 -p 1025:25 maildev/maildev`
run 
`localhost:8080`

**Comment by elhose** [comment]
Your solution works great @johnny-silverhand. I guess you are right, the issue lied in port mismatch. Thank You all for help!

**Comment by GorskiAnthony** [comment]
Hello my solution :)
```shell
$ docker run -p 80:80 -p 25:25 maildev/maildev
MailDev webapp running at http://0.0.0.0:80
MailDev SMTP Server running at 0.0.0.0:25
```

**Comment by soulteary** [comment]
hi,  @veritem @elhose @DennisMaas @johnny-silverhand @GorskiAnthony   We updated a new version docker image, hope it helps you
https://github.com/maildev/maildev/issues/382
