### ISSUE TITLE
FIX READ.ME: mistakes at docker command

### ISSUE THREAD

**Issue by marshtupa** [maildev/maildev#351]
docker run -p 1080:80 -p 1025:25 maildev/maildev

You should expose 80 and 25 inner ports

**Comment by gh640** [comment]
https://github.com/maildev/maildev/pull/355 will fix this.

**Comment by soulteary** [comment]
hi, @marshtupa @gh640   We updated a new version docker image, hope it helps you
https://github.com/maildev/maildev/issues/382
