### ISSUE TITLE
Feature - log incoming mail to console

### ISSUE THREAD

**Issue by LoneRifle** [maildev/maildev#354]
Several of our repos at @opengovsg have benefitted from maildev, allowing devs running an application on their machine to send mails containing one-time passwords as if it were deployed to production.

Currently, it is tedious to visit maildev's dashboard to read a mail for a specific phrase or text as part of overall developer workflow. While this is easily [worked around](https://github.com/opengovsg/GoGovSG/blob/develop/Dockerfile.maildev-logging), it would be good if maildev has a CLI flag to log incoming mail to console out of the box.

**Comment by soulteary** [comment]
Thanks for the feedback, this feature has been implemented in the last version.

https://github.com/maildev/maildev/releases/tag/v2.0.0
