### ISSUE TITLE
maildev http server not working

### ISSUE THREAD

**Issue by subhadeep-123** [maildev/maildev#360]
Used this, command for setting up the HTTP server and the SMTP server but none of them is working.

`docker pull djfarrelly/maildev`
`docker run -p 1080:80 -p 1025:25 djfarrelly/maildev`

![image](https://user-images.githubusercontent.com/42332939/119138739-d6014900-ba5f-11eb-826d-9874d3827cc9.png)

**Comment by Bessonov** [comment]
Try:
```
docker run -p 80:80 -p 25:25 djfarrelly/maildev
```
instead.

**Comment by EricAskari** [comment]
> Used this, command for setting up the HTTP server and the SMTP server but none of them is working.
> 
> `docker pull djfarrelly/maildev`
> `docker run -p 1080:80 -p 1025:25 djfarrelly/maildev`
> 
> ![image](https://user-images.githubusercontent.com/42332939/119138739-d6014900-ba5f-11eb-826d-9874d3827cc9.png)

you are either using wrong docker image or you are in wrong place 😃
image is `maildev/maildev`

**Comment by lalik77** [comment]
I have the same issue , with docker .

**Comment by soulteary** [comment]
The problem is that the docker image uses the old code from two years ago.

I tried to create a new docker image based on the current code, and after running it, the default port is indeed as shown in the documentation. So we don't have to modify the port number in the documentation.

You can use this command to verify.

```bash
docker run -p 1080:1080 -p 1025:1025 soulteary/maildev:1.1.0
```

**Comment by soulteary** [comment]
hi,  @subhadeep-123 @ericaskari @Bessonov @lalik77 We updated a new version docker image, hope it helps you
https://github.com/maildev/maildev/issues/382
