### ISSUE TITLE
10 vulnerabilities (2 moderate, 3 high, 5 critical)

### ISSUE THREAD

**Issue by MaxR522** [maildev/maildev#362]
After i install maildev with this command: `sudo npm install -g maildev` I got 10 vulnerabilities (2 moderate, 3 high, 5 critical).
This is the full log: 

`npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated nodemailer@3.1.8: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/

added 118 packages, and audited 119 packages in 15s

1 package is looking for funding
  run `npm fund` for details

10 vulnerabilities (2 moderate, 3 high, 5 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
`

**Comment by bcis-kassel** [comment]
Is this project still maintained?

**Comment by MaxR522** [comment]
I don't even know! I hope so

**Comment by kgeis** [comment]
A good read: [npm audit: Broken by Design](https://overreacted.io/npm-audit-broken-by-design/)

**Comment by soulteary** [comment]
This issue is being fixed. https://github.com/maildev/maildev/pull/378

**Comment by soulteary** [comment]
Thanks for your feedback  @kgeis @MaxR522 @bcis-kassel 
This issue will be done in the next release, please pay attention to related issues

ref: https://github.com/maildev/maildev/issues/379 https://github.com/maildev/maildev/pull/378
