### ISSUE TITLE
Feature Request - Dispaly From Email Address

### ISSUE THREAD

**Issue by daviddickgrcc** [maildev/maildev#363]
Currently we can see the from address in the source and header information, but it would be very nice to see the from address in either the left sidebar by the date/to address information or in the text/html area when clicking on an email.

**Comment by soulteary** [comment]
This feature is included in our upcoming version, but the interface style needs to continue to be optimized.

You can pay attention to the v2.0.2 version, I hope it can help you. @daviddickgrcc 

https://github.com/maildev/maildev/issues/233
