### ISSUE TITLE
Security issue npm audit

### ISSUE THREAD

**Issue by SSANSH** [maildev/maildev#374]
is it possible to bump dependencies to the project maildev? npm audit command raise several critical issue.

`
xmlhttprequest-ssl
11 vulnerabilities (4 moderate, 1 high, 6 critical)
`
This is a dependency of the project

`
└─┬ maildev@1.1.0
  └─┬ socket.io@2.2.0
    └─┬ socket.io-client@2.2.0
      └─┬ engine.io-client@3.3.2
        └── xmlhttprequest-ssl@1.5.5
`

**Comment by soulteary** [comment]
Thanks for your feedback @SSANSH 
This issue will be done in the next release, please pay attention to related issues

ref: https://github.com/maildev/maildev/issues/379 https://github.com/maildev/maildev/pull/378
