### ISSUE TITLE
bug: Install maildev version 2

### ISSUE THREAD

**Issue by kossa** [maildev/maildev#390]
Hello,

When I run : `npm i -g maildev` and then `maildev --version` I got 1.1.0 why it does not pull the latest version (2.0.2)?

Thanks

<img width="444" alt="image" src="https://user-images.githubusercontent.com/1175584/159675227-7b105b81-1c7d-4911-97f9-bbbbc7c9674e.png">

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1175584/159660149-63fa628f-e1cf-425c-bc0d-0434c30a117d.png">

**Comment by idears-org** [comment]
It is not published yet
see https://www.npmjs.com/package/maildev

**Comment by soulteary** [comment]
Thanks for the feedback @kossa  , the founders of the project are testing and launching, and we are having some discussions, but due to our time zone differences, it may take a day or two for this action.

**Comment by kossa** [comment]
Thank you

**Comment by groenroos** [comment]
Until the package is updated on npm, as a workaround, you can install direct from GitHub;

```
npm i -g maildev/maildev
```

Or, in `package.json` (locked to the `v2.0.2` tag, so you don't get unreleased changes);

```
{
  "dependencies": {
    "maildev": "github:maildev/maildev#v2.0.2"
  }
}
```

**Comment by kossa** [comment]
Thank you @groenroos got it :)

![Uploading image.png…]()
