### ISSUE TITLE
Email display error 

### ISSUE THREAD

**Issue by danghieu90** [maildev/maildev#398]
Test mail not show correct:
![2022-03-26_00-08](https://user-images.githubusercontent.com/12055214/160168334-528cea17-8220-4d6f-b1ef-6ca14145b715.png)

Console log error:
![2022-03-26_00-09](https://user-images.githubusercontent.com/12055214/160168459-3b172ee3-6058-47cd-a4dd-720d79077898.png)

Same email show perfect with old maildev docker
![2022-03-26_00-12](https://user-images.githubusercontent.com/12055214/160169072-4fe9dbd1-9ea1-4a7c-b70a-ff8c0531862d.png)

Original test message attached:
[il3Q4M3X.eml.txt](https://github.com/maildev/maildev/files/8352547/il3Q4M3X.eml.txt)

**Comment by idears-org** [comment]
Seems the html content was rendered as plan text

**Comment by TigerTim** [comment]
+1

**Comment by dcrouch79** [comment]
Version 1.1.1 seems to be last working version.

**Comment by dcrouch79** [comment]
I'm using `maildev/maildev:1.1.1` docker image with success.

**Comment by djfarrelly** [comment]
Fixed in https://github.com/maildev/maildev/releases/tag/v2.0.4
