### ISSUE TITLE
Dockerfile HEALTHCHECK vs configuring the host/port for the web interface vs IPv4/IPv6

### ISSUE THREAD

**Issue by ankon** [maildev/maildev#407]
The healthcheck is configured to check "localhost:1080", which works iff the web interface is bound to port 1080 and "whatever-localhost-resolves-to".

Unfortunately this breaks for me (Intel mac + podman):
1. The default bind host is `0.0.0.0` (see https://github.com/maildev/maildev/blob/87eceb00c7c49e051b936e4c5279867a2cebf348/lib/web.js#L118)
2. podman sets up the world to support IPv4 and IPv6
3. The maildev container has/receives a `/etc/hosts` that resolves `localhost` to both `127.0.0.1` and `::1`
4. wget (and/or the underlying libc) has a preference for using IPv6 when it is available:

Log from wget (trimmed a bit to remove podman-compose noise):

```log
$ podman-compose exec maildev wget -O - http://localhost:1080/healthz
Connecting to localhost:1080 ([::1]:1080)
wget: can't connect to remote host: Connection refused
exit code: 1
```

## Workaround

I can set `MAILDEV_WEB_IP` to `::`.

## Expectation

"Things work just fine". But, that's not trivial I think:

1. The healthcheck config would need to know what the user configured?
2. IPv4/IPv6 is still quite confusing, and the goal of the project seems to be ease-of-use

So maybe this could be instead added to the documentation?

**Comment by michael-sanders** [comment]
The healthcheck also fails if you set the base-pathname to a non-default value via the `--base-pathname` option (or `MAILDEV_BASE_PATHNAME` env var).

**Comment by AndreasScharfCPB** [comment]
Same here. If I configure the ports via environment variable in a docker-compose file the healthcheck checks the wrong port.

**Comment by djfarrelly** [comment]
Should be fixed in the next release if it wasn't already fixed in the 2.x release line
