### ISSUE TITLE
HTML page is not rendered properly

### ISSUE THREAD

**Issue by GaneshanNT** [maildev/maildev#411]
The email template is not rendered properly in maildev inbox but the same email template is rendered properly if I ran directly in the browser.

Attached the screenshots for your reference

Maildev screen

<img width="992" alt="not rendered properly1" src="https://user-images.githubusercontent.com/26402630/164966488-71e41a56-fe24-4183-abf4-e0cc9633fd5d.png">

Email template

<img width="926" alt="rendered properly" src="https://user-images.githubusercontent.com/26402630/164966515-5e10f5d4-06f9-4352-9f9a-903d9a451aa8.png">

**Comment by dablurr** [comment]
Hey guys, 

Having the same issues with the HTML on my end too. Using the `latest` image from Docker.

**Comment by jkolarovic** [comment]
Hi everyone,
Same issue here !  :-)

**Comment by Huluti** [comment]
Hello! Having the same issue :)

**Comment by paxyknox** [comment]
We notice this issue happens when using swift and smtp but not gmail protocol.

**Comment by djfarrelly** [comment]
@GaneshanNT or anyone else who has experienced the same issue - can you provide steps/code or an email body to reproduce the error? With that we could add it to the test script and fix this one up. Thanks!

**Comment by danghieu90** [comment]
same issue https://github.com/maildev/maildev/issues/398

**Comment by djfarrelly** [comment]
Fixed in https://github.com/maildev/maildev/releases/tag/v2.0.4

**Comment by Couapy** [comment]
Tested, and it works well !
Thank's a lot for your work :+1:

**Comment by GaneshanNT** [comment]
Thank you!! ... it is working fine now

**Comment by pedrovagner** [comment]
When `latest` Docker image release will be updated?
