### ISSUE TITLE
Save Emails in a DB

### ISSUE THREAD

**Issue by jumoog** [maildev/maildev#44]
It should be possible to save emails. 

I want use MailDev for my Website as Email Server

**Comment by pkat** [comment]
I agree that maildev is geared toward development, however it would be convenient to have some sort of simple persistence, when you can't keep maildev always running and still want to view or compare previous emails. Something like [Redis] (https://www.npmjs.com/package/redis) may be really easy to implement for fast and simple storage.

**Comment by djfarrelly** [comment]
@pkat thanks for your thoughts! Adding a Redis adapter into the main project might lead to the desire to add other adapters like Memcached, SQLite, Mongo, etc. I'm totally open the idea of some persistance options, but maybe in the form of a plugin. Perhaps there could be some usage like:

```
$ maildev --storage=maildev-redis
$ maildev --storage=/path/to/custom-module
```
Which would use a compatible storage module either installed via npm or potentially something custom written that's API-compatible. What do you think?

**Comment by pkat** [comment]
Yeah that makes sense. Going the adapter router would keep things more modular and lightweight and allow for any number of data stores. Reminds me of [Nodemailer's](https://github.com/andris9/Nodemailer#available-transports) concept of transport method plugins.

**Comment by dlitty** [comment]
I too would like to see some kind of persistence; not because I want to keep them long term, but rather when developing and testing we need to be able refer to emails across process shutdowns / server reboots.  It can problematic to run a test on a system that generates email, make a change, then run it again - hoping to compare the results between the emails - if the process or server has shut down in the mean time.  

Even just writing them to files in a path other than /tmp would be very useful.

**Comment by donut87** [comment]
I kind of already explored that option
https://github.com/donut87/MailDev/tree/persistMails

**Comment by dlitty** [comment]
@donut87 - Did you stop using it because you no longer needed it, or because you changed to another tool?

**Comment by donut87** [comment]
We did not switch to another tool. I would not say we did not need it, but we changed the way we send mails and did not reimplement this.

**Comment by joshuaadickerson** [comment]
I like this idea for development. I don't daemonize my Docker containers when I'm developing so I can just kill and restart them quickly. I do all of them at once so there's no links or anything leftover. That means I kill my maildev container.

**Comment by mkweick** [comment]
Any plans to include this feature? I too would like to see some kind of persistence with emails after service restarts.

**Comment by oktapodia** [comment]
Sorry it's been a long time ago, we will look into it

**Comment by atapatel** [comment]
+1

**Comment by AmauryOrtega** [comment]
Looking forward to this :fire:

**Comment by aandis** [comment]
You can always do it yourself using maildev's [api](https://github.com/maildev/maildev/blob/master/docs/api.md).

**Comment by deep1639** [comment]
+1

**Comment by Phlegethonyarre** [comment]
+1
